[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "Gb9qweYG29LMabnNMkLA9b2W5iNGXR3EV7C6zrLQHa8J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/anon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
